services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 5000:5000

  database:
    image: postgis/postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  reverseproxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/local.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
